### ISSUE TITLE
导航栏跳转失效

### ISSUE THREAD

**Issue by Thesoul20** [MuiseDestiny/zotero-style#452]
**不礼貌不回复，直接关闭**
开启插件，选择PDF背景颜色后，左边的导航栏会失效，点击对应的标题不会跳转到PDF中对应的部分。并且这种BUG只有当PDF背景颜色设置为暗色（从上往下数第二个，后文同）、夜色（第三个）、深色时会出现该BUG.设置为其它颜色时可以正常的跳转。

![暗色](https://github.com/MuiseDestiny/zotero-style/assets/49742133/4ead9fd6-a590-4e4f-9273-69e7defb8ef0)

![夜色](https://github.com/MuiseDestiny/zotero-style/assets/49742133/7e074eff-4386-4696-a58c-8457b0155a39)

![深色](https://github.com/MuiseDestiny/zotero-style/assets/49742133/71041277-50cb-4e7b-a35a-3bdb3f8f3a10)

Versions:
zotero 7.0.0  6.0.26
其它插件： Zotero PDF translate  1.0.22
OS: Kubuntu 22.10

**Comment by Thesoul20** [comment]
然而在另外一个插件——[Night for Zotero](https://github.com/tefkah/zotero-night)上，可以在对PDF背景进行反色后，保持左边的侧边栏跳转的有效性。

**Comment by LeoJhonSong** [comment]
虽然我不知道这个bug的原因, 但new bing告诉我zotero的pdf阅读器是基于pdf.js实现的, 然后我在浏览器里对着一个拿pdf.js打开的pdf调了调, 发现这样是可行的, 侧边栏目录是可以点击跳转的😁:
<img width="356" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/37630203/d04a81d2-f5d8-4de9-88c8-f9f29606c056">
```css
.pdfViewer {
  background: #222; /* 👈 这个是pdf页面外的背景的颜色 */
}
.canvasWrapper {
  filter: invert(64%) contrast(228%) brightness(80%) hue-rotate(180deg);
}
```
<img width="1381" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/37630203/5454d007-8bee-46d2-a062-345ef38cf886">
